In [1]:
import numpy as np

# Populate arrays with specific numbers

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [5]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [7]:
zeros_array = np.zeros
print(zeros_array)

<built-in function zeros>


In [8]:
print(np.zeros)

<built-in function zeros>


# Populate arrays with sequences of numbers

In [12]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


notice that np.arange generates a sequence that includes the lower bount 5, but not the upper bount 12.

# Populate arrays with random numbers

In [14]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[95 63 60 66 80 81]


Note that the highest generated integer np.random.randint is one less than the high argument.

In [16]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.12250963 0.63154083 0.81263947 0.89082342 0.21228865 0.54132465]


# Mathematical Operations on NumPy Operands

In [17]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.12250963 2.63154083 2.81263947 2.89082342 2.21228865 2.54132465]


In [18]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[285 189 180 198 240 243]


# Task 1: Create a linear dataset

The goal is to create a simple dataset consisting of a single feature and a label as follows:

1. assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array names feature.
2. Assign 15 values to NumPy array named label such that: label = 3*feature + 4

In [21]:
feature = np.arange(6,21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [33]:
label = 3 * feature + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


# Task 2: Add some noise to the dataset

Random noise makes the dataset a bit more realistig. We focus on each element of the label array.

In [34]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = noise + label
print(label)

[-0.72437761  1.97154796  1.1529381   0.90920599 -1.23601572  1.69527266
  1.32591828 -0.65379864  1.59583116 -1.65328886  1.20395324 -0.99931586
  0.63546582  1.06579443  1.5933591 ]
[21.27562239 26.97154796 29.1529381  31.90920599 32.76398428 38.69527266
 41.32591828 42.34620136 47.59583116 47.34671114 53.20395324 54.00068414
 58.63546582 62.06579443 65.5933591 ]
